name: dexeca
version: "1.3.0"
homepage: https://github.com/brad-jones/dexeca
description: A dartlang child process executor inspired by https://github.com/sindresorhus/execa

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.7.0

dev_dependencies:
  drun: ^2.0.2
  test: ^1.14.1
  pedantic: ^1.8.0
